
CREATE TABLE hospitals (
    uid INT(128) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    BName VARCHAR(128) NOT NULL,
    BCode VARCHAR(128) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE appoint (
    uid INT(128) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    metPson VARCHAR(128) NOT NULL,
    tableData VARCHAR(128) NOT NULL,
    whoMet VARCHAR(128) NOT NULL,
    metMail VARCHAR(128) NOT NULL,
    metNumber VARCHAR(128) NOT NULL,
    metDate VARCHAR(128) NOT NULL,
    metTime VARCHAR(128) NOT NULL,
    metType VARCHAR(128) NOT NULL,
    metHed VARCHAR(128) NOT NULL,
    metDetail MEDIUMTEXT NOT NULL,
    metExpire VARCHAR(128) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE aptsuccess (
    uid INT(128) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    metPson VARCHAR(128) NOT NULL,
    tableData VARCHAR(128) NOT NULL,
    whoMet VARCHAR(128) NOT NULL,
    metMail VARCHAR(128) NOT NULL,
    metDate VARCHAR(128) NOT NULL,
    metTime VARCHAR(128) NOT NULL,
    metType VARCHAR(128) NOT NULL,
    metHed VARCHAR(128) NOT NULL,
    metDetail MEDIUMTEXT NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE userverify (
    uid INT(128) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Userinfo VARCHAR(128) NOT NULL,
    UserinfoCode VARCHAR(128) NOT NULL,
    User VARCHAR(128) NOT NULL,
    UserCode VARCHAR(128) NOT NULL,
    Number VARCHAR(128) NOT NULL,
    Email VARCHAR(128) NOT NULL,
    Gender VARCHAR(128) NOT NULL,
    Password VARCHAR(128) NOT NULL,
    userSelector VARCHAR(128) NOT NULL,
    userToken VARCHAR(128) NOT NULL,
    userExpire VARCHAR(128) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE resetpwd (
    rstId INT(128) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    rstUser VARCHAR(128) NOT NULL,
    rstTbl VARCHAR(128) NOT NULL,
    rstSelector VARCHAR(128) NOT NULL,
    rstExpire VARCHAR(128) NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
